### ISSUE TITLE
FFR Integration Missed Files

### ISSUE THREAD

**Issue by sivaprakasaman** [HeinzLabPurdue/NEL#38]

**Comment by hausersn1** [comment]
Major changes on this branch:

1. Live Plotting now working on FFR run levels. Free running plots, but seems to just plot first run. We always run levels though, so not a huge priority to fix.
2. nel_matlab\FFR is now deprecated (-> xFFR in case we need some files). No longer added to path, all files for FFR are now in AEP\FFR. To do this, a circuit file was changed, since it pulled stim wav files from an old directory.
